[package]
name = "softposit"
version = "0.1.0"
authors = ["Andrey Zgarbul <zgarbul.andrey@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"

[dependencies.libm]
version = "0.1.2"
optional = true

[features]
default = ["float_convert"]
float_convert = ["libm"]

[dev-dependencies]
rand = "0.6"
