[package]
name = "softposit"
version = "0.1.1"
authors = ["Andrey Zgarbul <zgarbul.andrey@gmail.com>"]
description = "Implementation of Posit numbers"
repository = "https://gitlab.com/burrbull/softposit-rs"
keywords = ["posit", "unum"]
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies.num-traits]
version = "0.2"
optional = true

[dependencies.libm]
version = "0.1.2"
optional = true

[features]
default = ["float_convert"]
float_convert = ["libm"]

[dev-dependencies]
rand = "0.6"
