on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy -- -D warnings
